- name: play level variables
  hosts: local
  connection: local
  tasks:
   - name: print course information
     ansible.builtin.debug:
      msg: "Hello Ansible, course durarion is 120 hours, course trainer is shiva"