- name: play level variables
  hosts: local
  connection: local
  vars: 
   COURSE: Ansible
   DURATION: 120 HOURS
   TRAINER: Sivakumar
  tasks:

   - name: print course information
     ansible.builtin.debug:
      msg: "Hello, I'm learning {{ COURSE}}, course durarion is {{ DURATION}}, course trainer is {{ TRAINER }}"