- name: variables from playlevel 
  hosts: local
  connection: local
  vars_files:
  - COURSE.yaml
  tasks:
   - name: Check variables
     ansible.builtin.debug:
      msgs: I'm learning {{ COURSE }}, course duration is {{ DURATION }} and trainer is {{ TRAINER }}