- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME 
    prompt: "please enter username"
    private: false #user can't see the information

  - name: PASSWORD 
    prompt: "please enter password"
    private: false

  tasks:
  - name: printing user information
    Ansible.builtin.debug:
     msg: "Hello username is: {{ USERNAME }}, password is {{ PASSWORD }}"
    