- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
     msg: "Helo, I'm learninig {{ COURSE }}, Course duration is {{ DURATION }} and trainer is {{ TRAINER }}"