- name: checking the datatypes
  hosts: local
  connection: local
  vars:
   NAME: JoinDevops
  tasks:
   - name: printing the key value pair
     ansible.builtin.debug:
      msg: "Name : {{ NAME }}"