- name: check number is less than 20 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: enter the number please
    private: false
  # vars: 
  #  my_number: 15
  tasks:
  - name: print this is less than 20 or not
    ansible.builtin.debug:
     msg: "given number {{ my_number }} is less than 20"
    when: my_number | int < 20 

  - name: print this is less than 20 or not
    ansible.builtin.debug:
     msg: "given number is {{ my_number }} is greater than are equal to 20"
    when: my_number | int >= 20 #condition statement


