- name: check number is less than 20 or not
  hosts: local
  connection: local
  vars: 
   my_numer: 15
  tasks:
  - name: print this is less than 20 or not
    ansible.builtin.debug:
     msg: "given number is {{ my_number }} is less than 20"
    when: my_number < 20 

  - name: print this is less than 20 or not
    ansible.builtin.debug:
     msg: "given number is {{ my_number }} is greater than are equal to 20"
    when: my_number | int >= 20 #condition statement


