- name: Demo on functions
  hosts: local
  connection: local
  tasks: 
  - name: print the default variables
    ansible.builtin.debug:
     msg: "Hello, {{ DevOps | default('AWS') }}"
  - name: convert to upper case
    vars: 
     greeting: "Hello Neeraj"
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"

