- name: Demo on functions
  hosts: local
  connection: local
  tasks: 
  - name: print the default variables
    ansible.builtin.debug:
     msg: "Hello, {{ DevOps | default('AWS') }}"
  - name: convert to upper case
    vars: 
     greeting: "Hello Neeraj"
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"

  - name: convert to lower
    vars: 
     greeting: "Hello Ramesh"
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"

  - name: get the values in uniques
    vars: 
     values: [3,5,1,9,8,4]
    ansible.builtin.debug:
     msg: "Ascending order is : {{ values | unique}}"

  

