- name: Demo on functions
  hosts: local
  connection: local
  tasks: 
  - name: print the default variables
    ansible.builtin.debug:
     msg: "Hello, {{ DevOps | default('AWS') }}"
  - name: convert to upper case
    vars: 
     greeting: "Hello Neeraj"
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"

  - name: convert to lower
    vars: 
     greeting: "Hello Ramesh"
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"

  - name: get the values in uniques
    vars: 
     values: [3,5,1,9,8,1,3,4]
    ansible.builtin.debug:
     msg: "Get the unique values is : {{ values | unique}}"

  - name: get the min and max values
    vars: 
     values: [3,5,1,91,82,1,3,44]
    ansible.builtin.debug:
     msg: "min : {{ values | min }}, max : {{ values | max }}"

  - name: convert map to list
    vars:
      course:
        name: DevOps with AWS
        duration: 120
        trainer: sivakumar reddy
    ansible.builtin.debug:
      msg: " course info: {{ course | dict2items }}"
  - name: convert list to map
    vars:
      course:
       - {'key': 'name', 'value': 'DevOps with AWS'}
       - {'key': 'duration', 'value': 120}
       - {'key': 'trainer', 'value': 'sivakumar reddy'}
    ansible.builtin.debug:
      msg: " course info: {{ course | items2dict }}"

  - name: check ip address
    vars:
      myip: "255.366.002"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"
  

