- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: redirect output to the file
     #ansible.builtin.command: "ls -ltr > /tmp/output.txt "
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt "
    register: output
  
  - name: print the output
    ansible.builtin.debug:
     msg: "{{ output }}"

   
     